services:
  trade-db:
    image: mcr.microsoft.com/mssql/server
    container_name: trade-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Tr1c0lor
    restart: always
    ports:
      - "1433:1433"

  message-broker:
    image: rabbitmq:management
    container_name: message-broker
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  banking.trading.api:
    image: banking.trading.api
    depends_on:
      - trade-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: src/Banking.Trading.API/Dockerfile
    ports:
      - "5050:8080"
      - "5051:8081"
